apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
type: Opaque
stringData:
  MENSAJE: "Hola equipo de Redes, prueba en tiempo real"
  db-password: "S3cr3t0-D3-Pru3ba"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-secretos-svc
spec:
  type: LoadBalancer
  selector:
    app: demo-secretos
  ports:
  - port: 80
    targetPort: 9898
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-secretos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-secretos
  template:
    metadata:
      labels:
        app: demo-secretos
    spec:
      containers:
      - name: podinfo
        image: ghcr.io/stefanprodan/podinfo:6.7.1
        ports:
        - containerPort: 9898
        env:
        - name: PODINFO_UI_MESSAGE
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: MENSAJE
        volumeMounts:
        - name: credenciales
          mountPath: /etc/secretos
          readOnly: true
      volumes:
      - name: credenciales
        secret:
          secretName: demo-secret